seeder:
  file: ./seeder/seeder.rb
parsers:
  - page_type: listings
    file: ./parsers/listings.rb
  - page_type: products
    file: ./parsers/products.rb
exporters:
  - file: ./exporters/products_json.yaml 