seeder:
  file: ./seeder/seeder.rb
  disabled: false
parsers:
  - page_type: listings
    file: ./parsers/listings.rb
    disabled: false
  - page_type: products
    file: ./parsers/products.rb
    disabled: true
exporters:
  - file: ./exporters/products_json.yaml 
    disabled: true